config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  post 'welcome/create' => 'welcome#create'

end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name, :validate => true
  attribute :company, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i

  attribute :message
  attribute :nickname, :captcha => true

  def headers
    {
      :subject => "New Contact Form Submission",
      :to => "info@cardseliquid.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @contact = ContactForm.new
  end

  def create
    @contact = ContactForm.new(params[:contact_form])
    @contact.request = request
    if @contact.deliver
      flash.now[:success] = 'Thank you for contacting us. We will get in touch soon.'
      render :index
    else
      flash.now[:alert] = 'Cannot send message.'
      render :index
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Cards Premium E-Liquid" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="main-banner">
      <div class="row">
        <div class="small-12 columns">
          <div class="logo">
            <%= link_to image_tag('Cards-Logo.png'), root_url %>
          </div>
        </div>
      </div>
    </div>
    <div class="contain-to-grid">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1>
              <a href="#"></a>
            </h1>
          </li>
          <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>
        <section class="top-bar-section">
          <!-- Left Nav Section -->
          <ul class="left">
            <li><a href="#menu" class="scroll">Our Menu</a></li>
            <li><a href="#contact" class="scroll">Contact Us</a></li>
          </ul>
        </section>
      </nav>
    </div>

    <%= yield %>
    <footer>
      <div class="row">
        <div class="small-12 columns">
          <p>
            &copy; 2014 Cards E-Liquid. All Rights Reserved.
          </p>
        </div>
      </div>
    </footer>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="row">
  <div class="small-12 medium-8 columns">
    <%= image_tag('cards.jpg') %>
  </div>
  <div class="small-12 medium-4 columns">
    <h1>Welcome to Cards</h1>
    <p>
      Cards E-Liquid creates premium e-liquid right in the USA, with flavors to satisfy any electronic cigarette user. This isn't your run-of-the-mill e-liquid.
      Our menu consists of carefully selected and crafted flavors to ensure a high-quality taste and experience, and with nicotine levels ranging
      from 0-24mg everybody can enjoy the Cards line of signature e-liquid.
    </p>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <h1 id="menu">Our Menu</h1>
    <div class="row">
      <div class="small-6 medium-3 columns">
        <div class="suit">
          <%= image_tag('hearts.png') %> 
        </div>
        <h2>Hearts</h2>
        <p>
          A creamy, fruity flavor designed to redefine the taste of strawberry candy.
        </p>
      </div>
      <div class="small-6 medium-3 columns">
        <div class="suit">
          <%= image_tag('spades.png') %>
        </div>
        <h2>Spades</h2>
        <p>
          Awaken your taste buds with a fresh-baked American classic - Apple Pie.
        </p>
      </div>
      <div class="small-6 medium-3 columns">
        <div class="suit">
          <%= image_tag('diamonds.png') %>
        </div>
        <h2>Diamonds</h2>
        <p>
          A rich peanut butter blend laced with fresh, ripe strawberries and bananas.
        </p>
      </div>
      <div class="small-6 medium-3 columns">
        <div class="suit">
          <%= image_tag('clubs.png') %>
        </div>
        <h2>Clubs</h2>
        <p>
          Your favorite coffee house blend, intended to stimulate your sixth sense.
        </p>
      </div>
    </div>
    <div class="row">
      <div class="small-6 small-centered medium-3 columns">
        <div class="suit">
          <%= image_tag('joker.png') %>
        </div>
        <h2>Jokers</h2>
        <p>
          Jokers are unpredicable and surprising. They can't be beat. Jokers are wild!
        </p>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <h1 id="contact">Contact Us</h1>
    <div class="row">
      <div class="small-12 medium-8 columns">
      <% flash.each do |key, value| %>
          <div data-alert class="alert-box <%= key.to_s %>">
            <%= value %>
            <a href="#" class="close">&times;</a>
          </div>
        <% end %>
        <%= form_for @contact, :url => welcome_create_path(@contact) do |f| %>
          <%= f.label :name %><br>
          <%= f.text_field :name, :required => true %>
          <%= f.label :company %><br>
          <%= f.text_field :company, :required => true %>
          <%= f.label :email %><br>
          <%= f.text_field :email, :required => true %>
          <%= f.label :message %><br>
          <%= f.text_area :message, :required => true %>
          <div class="hidden">
            <%= f.text_field :nickname %>
          </div>
          <%= f.submit 'Send message', :class => "button small" %>
        <% end %>
      </div>
      <div class="small-12 medium-4 columns">
        <ul class="vcard">
          <li class="fn">Cards E-Liquid</li>
          <li class="email"><a href="mailto:info@cardseliquid.com">info@cardseliquid.com</a></li>
          <li class="phone-number"><a href="tel:+15133422470">(513) 342-2470</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>